export const region = [
    {"region_code":"01","name":"REGION I (ILOCOS REGION)"},
    {"region_code":"02","name":"REGION II (CAGAYAN VALLEY)"},
    {"region_code":"03","name":"REGION III (CENTRAL LUZON)"},
    {"region_code":"04","name":"REGION IV-A (CALABARZON)"},
    {"region_code":"05","name":"REGION V (BICOL REGION)"},
    {"region_code":"06","name":"REGION VI (WESTERN VISAYAS)"},
    {"region_code":"07","name":"REGION VII (CENTRAL VISAYAS)"},
    {"region_code":"08","name":"REGION VIII (EASTERN VISAYAS)"},
    {"region_code":"09","name":"REGION IX (ZAMBOANGA PENINSULA)"},
    {"region_code":"10","name":"REGION X (NORTHERN MINDANAO)"},
    {"region_code":"11","name":"REGION XI (DAVAO REGION)"},
    {"region_code":"12","name":"REGION XII (SOCCSKSARGEN)"},
    {"region_code":"13","name":"NATIONAL CAPITAL REGION (NCR)"},
    {"region_code":"14","name":"CORDILLERA ADMINISTRATIVE REGION (CAR)"},
    {"region_code":"15","name":"AUTONOMOUS REGION IN MUSLIM MINDANAO (ARMM)"},
    {"region_code":"16","name":"REGION XIII (Caraga)"},
    {"region_code":"17","name":"REGION IV-B (MIMAROPA)"}
];


export const province = [
    {"id":"0209","name":"BATANES","region_code":"02"},
    {"id":"0128","name":"ILOCOS NORTE","region_code":"01"},
    {"id":"0129","name":"ILOCOS SUR","region_code":"01"},
    {"id":"0133","name":"LA UNION","region_code":"01"},
    {"id":"0155","name":"PANGASINAN","region_code":"01"},
    {"id":"0215","name":"CAGAYAN","region_code":"02"},
    {"id":"0231","name":"ISABELA","region_code":"02"},
    {"id":"0250","name":"NUEVA VIZCAYA","region_code":"02"},
    {"id":"0257","name":"QUIRINO","region_code":"02"},
    {"id":"0308","name":"BATAAN","region_code":"03"},
    {"id":"0314","name":"BULACAN","region_code":"03"},
    {"id":"0349","name":"NUEVA ECIJA","region_code":"03"},
    {"id":"0369","name":"TARLAC","region_code":"03"},
    {"id":"0371","name":"ZAMBALES","region_code":"03"},
    {"id":"0377","name":"AURORA","region_code":"03"},
    {"id":"0410","name":"BATANGAS","region_code":"04"},
    {"id":"0421","name":"CAVITE","region_code":"04"},
    {"id":"0434","name":"LAGUNA","region_code":"04"},
    {"id":"0456","name":"QUEZON","region_code":"04"},
    {"id":"0458","name":"RIZAL","region_code":"04"},
    {"id":"0505","name":"ALBAY","region_code":"05"},
    {"id":"0516","name":"CAMARINES NORTE","region_code":"05"},
    {"id":"0517","name":"CAMARINES SUR","region_code":"05"},
    {"id":"0520","name":"CATANDUANES","region_code":"05"},
    {"id":"0541","name":"MASBATE","region_code":"05"},
    {"id":"0562","name":"SORSOGON","region_code":"05"},
    {"id":"0604","name":"AKLAN","region_code":"06"},
    {"id":"0606","name":"ANTIQUE","region_code":"06"},
    {"id":"0619","name":"CAPIZ","region_code":"06"},
    {"id":"0630","name":"ILOILO","region_code":"06"},
    {"id":"0645","name":"NEGROS OCCIDENTAL","region_code":"06"},
    {"id":"0679","name":"GUIMARAS","region_code":"06"},
    {"id":"0712","name":"BOHOL","region_code":"07"},
    {"id":"0722","name":"CEBU","region_code":"07"},
    {"id":"0746","name":"NEGROS ORIENTAL","region_code":"07"},
    {"id":"0761","name":"SIQUIJOR","region_code":"07"},
    {"id":"0826","name":"EASTERN SAMAR","region_code":"08"},
    {"id":"0837","name":"LEYTE","region_code":"08"},
    {"id":"0848","name":"NORTHERN SAMAR","region_code":"08"},
    {"id":"0860","name":"SAMAR (WESTERN SAMAR)","region_code":"08"},
    {"id":"0864","name":"SOUTHERN LEYTE","region_code":"08"},
    {"id":"0878","name":"BILIRAN","region_code":"08"},
    {"id":"0972","name":"ZAMBOANGA DEL NORTE","region_code":"09"},
    {"id":"0973","name":"ZAMBOANGA DEL SUR","region_code":"09"},
    {"id":"0983","name":"ZAMBOANGA SIBUGAY","region_code":"09"},
    {"id":"0997","name":"CITY OF ISABELA","region_code":"09"},
    {"id":"1013","name":"BUKIDNON","region_code":"10"},
    {"id":"1018","name":"CAMIGUIN","region_code":"10"},
    {"id":"1035","name":"LANAO DEL NORTE","region_code":"10"},
    {"id":"1042","name":"MISAMIS OCCIDENTAL","region_code":"10"},
    {"id":"1043","name":"MISAMIS ORIENTAL","region_code":"10"},
    {"id":"1123","name":"DAVAO DEL NORTE","region_code":"11"},
    {"id":"1124","name":"DAVAO DEL SUR","region_code":"11"},
    {"id":"1125","name":"DAVAO ORIENTAL","region_code":"11"},
    {"id":"1182","name":"COMPOSTELA VALLEY","region_code":"11"},
    {"id":"1186","name":"DAVAO OCCIDENTAL","region_code":"11"},
    {"id":"1247","name":"COTABATO (NORTH COTABATO)","region_code":"12"},
    {"id":"1263","name":"SOUTH COTABATO","region_code":"12"},
    {"id":"1265","name":"SULTAN KUDARAT","region_code":"12"},
    {"id":"1280","name":"SARANGANI","region_code":"12"},
    {"id":"1298","name":"COTABATO CITY","region_code":"12"},
    {"id":"1339","name":"CITY OF MANILA","region_code":"NCR"},
    {"id":"1374","name":"NCR, SECOND DISTRICT","region_code":"NCR"},
    {"id":"1375","name":"NCR, THIRD DISTRICT","region_code":"NCR"},
    {"id":"1376","name":"NCR, FOURTH DISTRICT","region_code":"NCR"},
    {"id":"1401","name":"ABRA","region_code":"14"},
    {"id":"1411","name":"BENGUET","region_code":"14"},
    {"id":"1432","name":"KALINGA","region_code":"14"},
    {"id":"1444","name":"MOUNTAIN PROVINCE","region_code":"14"},
    {"id":"1481","name":"APAYAO","region_code":"14"},
    {"id":"1536","name":"LANAO DEL SUR","region_code":"15"},
    {"id":"1538","name":"MAGUINDANAO","region_code":"15"},
    {"id":"1566","name":"SULU","region_code":"15"},
    {"id":"1570","name":"TAWI-TAWI","region_code":"15"},
    {"id":"1602","name":"AGUSAN DEL NORTE","region_code":"16"},
    {"id":"1603","name":"AGUSAN DEL SUR","region_code":"16"},
    {"id":"1667","name":"SURIGAO DEL NORTE","region_code":"16"},
    {"id":"1668","name":"SURIGAO DEL SUR","region_code":"16"},
    {"id":"1685","name":"DINAGAT ISLANDS","region_code":"16"},
    {"id":"1740","name":"MARINDUQUE","region_code":"17"},
    {"id":"1751","name":"OCCIDENTAL MINDORO","region_code":"17"},
    {"id":"1752","name":"ORIENTAL MINDORO","region_code":"17"},
    {"id":"1753","name":"PALAWAN","region_code":"17"},
    {"id":"1759","name":"ROMBLON","region_code":"17"}
  ];
  


