import { UserTransactionHistory } from '@/lib/types/userType'

export const UserTransactionData : UserTransactionHistory[] = [
    {
        tRef: 'Ref1',
        tName: 'Transaction 1',
        tPrice: 100,
        tDate: new Date('2023-01-01'),
        providerId: 'ProviderID1',
        providerName: 'Provider 1',
        providerNumber: '1112223333',
        providerAddress: '101 Elm St',
    },
    {
        tRef: 'Ref2',
        tName: 'Transaction 2',
        tPrice: 200,
        tDate: new Date('2023-02-01'),
        providerId: 'ProviderID2',
        providerName: 'Provider 2',
        providerNumber: '2223334444',
        providerAddress: '202 Oak St',
    },
    {
        tRef: 'Ref3',
        tName: 'Transaction 3',
        tPrice: 300,
        tDate: new Date('2023-03-01'),
        providerId: 'ProviderID3',
        providerName: 'Provider 3',
        providerNumber: '3334445555',
        providerAddress: '303 Main St',
    },
    {
        tRef: 'Ref4',
        tName: 'Transaction 4',
        tPrice: 400,
        tDate: new Date('2023-04-01'),
        providerId: 'ProviderID4',
        providerName: 'Provider 4',
        providerNumber: '4445556666',
        providerAddress: '404 Maple St',
    },
    {
        tRef: 'Ref5',
        tName: 'Transaction 5',
        tPrice: 500,
        tDate: new Date('2023-05-01'),
        providerId: 'ProviderID5',
        providerName: 'Provider 5',
        providerNumber: '5556667777',
        providerAddress: '505 Pine St',
    },
    {
        tRef: 'Ref6',
        tName: 'Transaction 6',
        tPrice: 600,
        tDate: new Date('2023-06-01'),
        providerId: 'ProviderID6',
        providerName: 'Provider 6',
        providerNumber: '6667778888',
        providerAddress: '606 Elm St',
    },
    {
        tRef: 'Ref7',
        tName: 'Transaction 7',
        tPrice: 700,
        tDate: new Date('2023-07-01'),
        providerId: 'ProviderID7',
        providerName: 'Provider 7',
        providerNumber: '7778889999',
        providerAddress: '707 Oak St',
    },
    {
        tRef: 'Ref8',
        tName: 'Transaction 8',
        tPrice: 800,
        tDate: new Date('2023-08-01'),
        providerId: 'ProviderID8',
        providerName: 'Provider 8',
        providerNumber: '8889990000',
        providerAddress: '808 Maple St',
    },
    {
        tRef: 'Ref9',
        tName: 'Transaction 9',
        tPrice: 900,
        tDate: new Date('2023-09-01'),
        providerId: 'ProviderID9',
        providerName: 'Provider 9',
        providerNumber: '9990001111',
        providerAddress: '909 Pine St',
    },
    {
        tRef: 'Ref10',
        tName: 'Transaction 10',
        tPrice: 1000,
        tDate: new Date('2023-10-01'),
        providerId: 'ProviderID10',
        providerName: 'Provider 10',
        providerNumber: '1234567890',
        providerAddress: '1010 Oak St',
    },
]